site_name: OpinionNet Documentation
site_description: Internal documentation for OpinionNet
site_url: ''

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css
  - assets/styles/extra.css


# Repository info
repo_name: RadicHUB/AWS-Opinion.net
repo_url: https://github.com/RadicHUB/AWS-Opinion.net
remote_name: upstream
edit_uri: edit/main/docs/

# We have to disable this otherwise relative linking between pages
# fails if you've moved directories. This gives us slightly less nice
# urls.
use_directory_urls: false

# Configuration
theme:
  name: material
  custom_dir: docs/theme
  icon:
    logo: material/cloud
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  # The instant feature compiles this as a single page app which makes
  # it so that the page doesn't need to refresh when opening a
  # url. This provides a nicer reading experience.
  features:
    - instant
  palette:
    primary: default
    accent: default

plugins:
    - search
    - macros
    - diagrams
    - mkdocs-jupyter
    #- git-revision-date-localized

# Extensions
markdown_extensions:
  - meta
  - admonition
  - plantuml_markdown
  - mkdocs_graphviz
  - toc:
      permalink: true
  - pymdownx.tasklist:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Home: index.md
